---
- name: restart prometheus
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted

- name: reload prometheus
  become: true
  systemd:
    name: prometheus
    state: reloaded

- name: restart node exporter
  become: true
  systemd: 
    name: node_exporter
    state: restarted
