---

- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: "{{ prometheus_db_dir }}"
    
- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- name: download prometheus binary to local folder
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.44.0.linux-amd64.tar.gz"

- name: unpack prometheus binaries
  unarchive:
    src: "/tmp/prometheus-2.44.0.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-2.44.0.linux-amd64/prometheus"
    remote_src: yes

- name: propagate official prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-2.44.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  with_items:
  - prometheus
  - promtool
  notify:
  - restart prometheus

- name: propagate official console templates
  copy:
    src: "/tmp/prometheus-2.44.0.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: root
    group: root
    remote_src: yes
  with_items:
      - console_libraries
      - consoles

- name: create systemd service unit
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus

- name: load prometheus configuration
  template: 
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: 0644
  notify:
    - restart prometheus
