---
- name: create nodeusr system group
  group:
    name: nodeusr
    system: true
    state: present

- name: create node exporter system user
  user:
    name: nodeusr
    system: true
    shell: "/usr/sbin/nologin"
    group: nodeusr
    createhome: false
    home: "{{ prometheus_db_dir }}"

- name: download node exporter binary to local folder
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.5.0.linux-amd64.tar.gz"

- name: unpack node exporter binaries
  unarchive:
    src: "/tmp/node_exporter-1.5.0.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: propagate official prometheus and promtool binaries
  copy:
    src: "/tmp/node_exporter-1.5.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    owner: nodeusr
    group: nodeusr
    remote_src: yes

- name: create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node exporter

