- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install package musl
  apt:
    name: "{{ item }}"
    state: latest
  loop:
  - musl
  - vim
